---

- name: "Install SELinux packages"
  yum:
    name: "{{ selinux_packages }}"
    state: 'present'
    update_cache: 'yes'
    lock_timeout: 180

- name: "Set selinux - {{ selinux_state }}"
  selinux:
    conf: '{{ selinux_conf_path }}'
    state: '{{ selinux_state }}'
  register: selinux_status

- name: "Reboot all the hosts"
  shell: 'sleep 5 && reboot'
  async: 1
  poll: 0
  when:
    - selinux_status.reboot_required

- name: "Wait for the hosts to reconnect"
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when:
    - selinux_status.reboot_required