---

- name: "Install packages -- {{ yum_packages | join(', ') }}"
  yum:
    name: '{{ yum_packages }}'
    state: 'latest'
    update_cache: 'yes'
    lock_timeout: 180


- name: "Start and enable service iptables service"
  systemd:
    name: iptables
    state: started
    enabled: yes