---

- name: "Grab the starting of the line that has 'swap'"
  shell: cat /etc/fstab | grep -E '^#(.*)swap(.*)'
  register: results
  failed_when: "results.rc > 1" # in case of failure return code will be greater than 1. 0 means okay, 1 means returned nothing
  changed_when: false

- name: "Disable swap"
  shell: swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab
  when:
    - "results.stdout_lines | length == 0"

- name: "Reboot all the hosts"
  shell: 'sleep 5 && reboot'
  async: 1
  poll: 0
  when:
    - "results.stdout_lines | length == 0"

- name: "Wait for the hosts to reconnect"
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when:
    - "results.stdout_lines | length == 0"