---

- name: "Include RedHat task for docker setup"
  include_tasks: setup-RedHat.yaml

- name: "Install Docker"
  yum:
    name: "{{ docker_package }}"
    state: 'present'
    update_cache: 'yes'
    lock_timeout: 180
  notify: restart docker

- name: "Ensure Docker is started and enabled at boot"
  service:
    name: docker
    state: started
    enabled: yes

- name: "Ensure handlers are notified now to avoid firewall conflicts"
  meta: flush_handlers

- name: "Include task for docker-compose setup"
  include_tasks: docker-compose.yaml
  when: docker_install_compose | bool

- name: "Include task for docker-users setup"
  include_tasks: docker-users.yaml
  when: docker_users | length > 0