---

- name: "Configure Kubernetes repo"
  hosts: 'master,workers'
  roles:
    - kubernetes-repo


- name: "Setup Kubernetes"
  hosts: 'master,workers'
  roles:
    - kubernetes-setup


- name: "Setup Kubelet"
  hosts: 'master,workers'
  roles:
    - kubernetes-kubelet-setup


- name: "Setup Master node"
  hosts: 'master'
  roles:
    - kubernetes-master-setup


- name: "Setup Workers node (1/2)"
  hosts: "master"
  tasks:
    - name: "Get the kubeadm join command from the Kubernetes master"
      command: kubeadm token create --print-join-command
      changed_when: false
      register: kubernetes_join_command_result


- name: "Setup Workers node (2/2)"
  hosts: "workers"
  become: yes
  tasks:
    - name: "Set the kubeadm join command globally"
      set_fact:
        kubernetes_join_command: >
          {{ hostvars[groups['master'][0]]['kubernetes_join_command_result'].stdout }}
      when:
        - hostvars[groups['master'][0]]['kubernetes_join_command_result'].stdout is defined
      run_once: true

    - debug:
        msg: "{{ kubernetes_join_command }}"

    - name: "Join node to Kubernetes master"
      shell: >
        {{ kubernetes_join_command }}
        creates=/etc/kubernetes/kubelet.conf