---

- name: "Install packages -- {{ kubernetes_packages | join(', ') }}"
  yum:
    name: '{{ kubernetes_packages }}'
    state: 'present'
    update_cache: 'yes'
    lock_timeout: 180
  notify: restart kubelet


- name: "Ensure kubelet is started and enabled at boot"
  service:
    name: kubelet
    state: started
    enabled: true