---

- name: "Install packages -- {{ kubernetes_packages | join(', ') }}"
  yum:
    name: '{{ kubernetes_packages }}'
    state: 'latest'
    update_cache: 'yes'
    lock_timeout: 180
    disable_excludes: 'kubernetes'