---

- name: "Disable firewall in all the hosts"
  hosts: 'master,workers'
  roles:
    - disable-firewall

- name: "Disable selinux in all the hosts"
  hosts: 'master,workers'
  roles:
    - disable-selinux

- name: "Disable swap in all the hosts"
  hosts: 'master,workers'
  gather_facts: no
  roles:
    - disable-swap